develop:
  hostname: 35.75.243.239
  port: 22
  stage: develop
  roles:
    - app
  deploy_path: /var/www/shelter-admin-api
  branch: develop
  user : sc
  identityFile: ~/.ssh/aws-shelter-backend/shelter-backend-dev.pem
production:
  hostname: 35.75.243.239
  port: 22
  stage: production
  roles:
    - app
  deploy_path: /var/www/shelter-admin-api
  branch: main
  user : sc
  identityFile: ~/.ssh/aws-shelter-backend/shelter-backend-dev.pem
